### ISSUE TITLE
newline endings in record file have windows line endings and shouldnt

### ISSUE THREAD

**Issue by adamjohnwright** [reactome/reactome_chatbot#58]

**Comment by GFJHogue** [comment]
### **TLDR: I'll set the CSV line endings to LF.**

_Continue reading if you'd like to learn why Python uses CRLF for all CSVs by default..._

## RFC 4180

From the 1st paragraph of the Python csv doc:
> CSV format was used for many years prior to attempts to describe the format in a standardized way in [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180.html). The lack of a well-defined standard means that subtle differences often exist in the data produced and consumed by different applications.
> \- https://docs.python.org/3/library/csv.html#module-csv

RFC 4180 is basically the closest thing to a standard for CSV - the format used/preferred by most software, including Excel.
This is Python's default CSV dialect, called `excel`.
Hence, CRLF line endings are the standard behaviour for `csv.writer`.

In the RFC 4180 spec:
> 1.  Each record is located on a separate line, delimited by a line
       break (CRLF).  For example:
> ```
> aaa,bbb,ccc CRLF
> zzz,yyy,xxx CRLF
> ```
> \- https://datatracker.ietf.org/doc/html/rfc4180.html#section-2

In the Python `csv` doc:
> `Dialect.lineterminator`[¶](https://docs.python.org/3/library/csv.html#csv.Dialect.lineterminator)
> The string used to terminate lines produced by the [writer](https://docs.python.org/3/library/csv.html#csv.writer). It defaults to `\r\n`.
> \- https://docs.python.org/3/library/csv.html#csv.Dialect.lineterminator
